---
title: "My Background"
format: html
---

## Education
### Master of Science in Biolgical Sciences 
_Emphasis in Cell and Molecular Biology_

California State Polytechnic University, Pomona

Aug 2023-Dec 2025

### Bachelor of Science, Major in Biology 
University of La Verne

Aug 2019-Dec 2022

## Technical Laboratory Skills 
### Cell Culture & Experimental Techniques
-Mammalian cell culture (HL-60 human promyelocytic cell line)

-Differentiation of HL-60 cells into neutrophil-like cells (NLCs)

-Cell counting, viability assessment, and culture optimization

-Sterile technique and aseptic workflows

-Preparation of media, buffers, and experimental reagents

### Immunology & Functional Assays
-In vitro modeling of innate immune responses

-Phagocytosis assays using fluorescent beads

-Cell surface marker analysis (e.g., CD11b, RANKL)

-Cytokine secretion analysis using multiplex bead-based assays

-Sample processing and supernatant collection for downstream analysis

### Flow Cytometry & Microscopy
-Flow cytometry data acquisition and interpretation

-Gating strategies, controls, and quality control

-FlowJo and LEGENDplex data analysis

-Fluorescence and brightfield microscopy

-Imaging and interpretation of cellular responses

### Data Analysis & Research Tools 
-Statistical analysis in R (tidyverse, dplyr)

-Data visualization and figure preparation

-Reproducible research workflows

-Microsoft Office and Google Workspace

-GitHub for project documentation and portfolio hosting

## Teaching, Mentoring, and Training Experience

### Teaching Associate  
**BIO 1110L** Life Science Lab (F24)  
**BIO 1150L** Biology and Society (F25)

**BIO 2350L** Human Physiology Lab (F23, SP24)  
**BIO 1220L** Foundations of Biology: Evolution, Ecology, and Biodiversity (SP25)  
Department of Biological Sciences  
California State Polytechnic University, Pomona  
_Aug 2023 – Dec 2025_

---

### Training of Graduate and Undergraduate Lab Members  
Steve Alas Lab  
Department of Biological Sciences  
California State Polytechnic University, Pomona  
_Aug 2023 – Dec 2025_

---

### Math and Reading K-12 Tutor  
Step Up Tutoring  
_October 2024 – May 2025_

---

### CLASP Tutoring | Claremont, CA  
_October 2022 – December 2023_

---

### Boys and Girls Club | La Puente, CA  
_March 2019 – May 2019_


## Work Experience

**Student Assistant**, College of Business and Public Management, University of La Verne  
_Sep 2022 – Dec 2022_

**Patient Representative**, COPE Health Solutions – University of Texas Rio Grande  
_Sep 2021 – Oct 2022_

**Health Scholar**, COPE Health Scholars – Emanate Health  
_Mar 2021 – May 2022_